dry_run: true
scale_up_threshold: 50
scale_down_threshold: 10 
cooldown_period: 60  # Cooldown period in seconds, between scaling actions in the same region

allowed_regions:
  - "ams"
  - "lhr"
  - "sfo"
  - "fra"

excluded_regions:
  - "nrt"
  - "sin"

always_running_regions:
  - "iad"
  - "cdg"