dry_run: true
scale_up_threshold: 50
scale_down_threshold: 30 
cooldown_period: 300  # in seconds
fly_app_name: "your-app-name"

allowed_regions:
  - "ams"
  - "fra"
  - "lhr"

excluded_regions:
  - "sin"
  - "nrt"

always_running_regions:
  - "iad"
  - "cdg"