app = "placer-service"
primary_region = "sea"

[env]
  PORT = "8000"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 8000
    handlers = ["http"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "placer_service_data"
  destination = "/app/data"

[[mounts]]
  source = "placer_service_logs"
  destination = "/app/logs"
